-- MySQL Script generated by MySQL Workbench
-- Fri Feb 25 17:19:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_be_inclusive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_be_inclusive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_be_inclusive` DEFAULT CHARACTER SET utf8 ;
USE `db_be_inclusive` ;

-- -----------------------------------------------------
-- Table `db_be_inclusive`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_be_inclusive`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `categoria` ENUM('voluntario', 'paciente') NOT NULL,
  `avaliacao` ENUM('verde', 'azul', 'amarelo') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_be_inclusive`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_be_inclusive`.`tb_tema` (
  `id_tb_tema` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` ENUM('verde', 'azul', 'amarelo') NULL,
  PRIMARY KEY (`id_tb_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_be_inclusive`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_be_inclusive`.`tb_postagem` (
  `idtb_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(1000) NULL,
  `url_imagem` VARCHAR(45) NULL,
  `data` DATE NOT NULL,
  `tb_usuario_id` INT NOT NULL,
  `fk_tema` INT NOT NULL,
  PRIMARY KEY (`idtb_postagem`, `fk_tema`),
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_tema1_idx` (`fk_tema` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_be_inclusive`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_tema1`
    FOREIGN KEY (`fk_tema`)
    REFERENCES `db_be_inclusive`.`tb_tema` (`id_tb_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
